
sudo: required
language: java

jdk:
  - openjdk8

script:
  - ./gradlew fatJar

before_deploy:
    - mkdir MiningBuild
    - find . -name '*.jar' -exec cp {} ./MiningBuild \;
    - cd /home/travis/build/semantic-conflicts/mockito/MiningBuild
    - tar -zcvf result.tar.gz *
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: result.tar.gz
  name: fetchjar-585b06d890b5e78857a5c5d5a2301065c2cac08b
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    all_branches: true 
            